[package]
name = "bp-ntex"
version = "0.1.0"
edition = "2024"

[dependencies]
lazy_static = "1.4"
ntex = { version = "2.12.4", features = ["tokio"] }
thirtyfour = "0.35.0"
tokio = { version = "1.45.0", features = ["full"] }
